name: Build PDF

on:
  workflow_dispatch:
    inputs:
      csv:
        description: "CSV data"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write CSV file
        run: |
          echo "${{ github.event.inputs.csv }}" > lappar.csv

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: lappar.tex

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
